version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache: 
          key: app-{{ checksum "package.jason" }}
      - run:
          name: Install yarn
          command: npm install -g yarn
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.jason" }}
 